import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { getAllPosts, getPostsTopPage } from '@/lib/notionAPI'
import { SinglePost } from '../../components/Post/SinglePost'
import { GetStaticProps } from 'next'

const inter = Inter({ subsets: ['latin'] })

/** page番号の取得 */
export const getAtaticPaths: GetStaticProps = async () => {
    return {
        paths: [],
        fallback: "blocking"
    }
};

export const getStaticProps: GetStaticProps = async () => {
  const Posts = await getPostsTopPage(4);

  return {
    props: {
      Posts,
    },
    revalidate: 60,
  }
}

const BlogPageList({ Posts }) => {
  return (
    <div className='container h-full w-full mx-auto'>
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container w-full mt-16'>
        <h1 className='text-4xl font-medium text-center mb-16'>
          Notion Blog🚀
        </h1>
        {Posts.map((post, index) => (
          <div className='mx-4' key={index}>
            <SinglePost
              title={post.title}
              description={post.description}
              data={post.date}
              tags={post.tags}
              slug={post.slug}
            />
          </div>
        ))}
      </main>
    </div>
  )
}

export default BlogPageList;