import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { getAllPosts } from '@/lib/notionAPI'
import { SinglePost } from './components/Post/SinglePost'

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps = async () => {
  const allPosts = await getAllPosts();

  return {
    props: {
      allPosts,
    },
    revalidate: 60,
  }
}

export default function Home({ allPosts }) {
  return (
    <div className='container h-full w-full mx-auto'>
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container w-full mt-16'>
        <h1 className='text-5l font-medium text-center mb-16'>
          Notion Blog🚀
        </h1>
        {allPosts.map((post, index) => (
          <div className='mx-4' key={index}>
            <SinglePost
              title={post.title}
              description={post.description}
              data={post.date}
              tags={post.tags}
              slug={post.slug}
            />
          </div>
        ))}
      </main>
    </div>
  )
}
